model_type: "deterministic"
hf_model_name: "AutonLab/MOMENT-1-large"
device: cpu
freeze_embedder: true
freeze_encoder: true
freeze_head: true
head_dropout: 0.1
python_version: '3.11'
weight_decay: 0
context_window: 512