task:
  task_name: healthcare
  context_window: 512
  forecast_horizon: 64
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: nyc_covid_healthcare_multivariate.csv

# number of variates : 54
# number of time-steps : 2005