task:
  task_name: continuous
  context_window: 256
  forecast_horizon: 32
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: nividia_continuous_multivariate.csv

# number of variates : 5
# number of time-steps : 2514
