task:
  context_window: 64
  forecast_horizon: 16
  handle_missing: interpolate
  normalization_method: standard
  file_name: multivariate_nature_annually_global_carbon_budget_barbados.csv
  multivariate_target_variable_names:
  - population
  - gdp
  - co2
  - co2_per_capita
  - co2_per_gdp
  - co2_growth_abs
  - co2_growth_prct
  - coal_co2
  - oil_co2
  - gas_co2
  - cement_co2
  - flaring_co2
  - land_use_change_co2
  - co2_including_luc
  - co2_including_luc_per_capita
  - cumulative_co2
  - cumulative_co2_including_luc
  - methane
  - nitrous_oxide
  - total_ghg
  - primary_energy_consumption
  - energy_per_capita
  - share_global_co2
  - share_global_cumulative_co2
  - trade_co2
  - temperature_change_from_co2
  covariate_target_variable_name: co2
  covariate_variable_names:
  - population
  - gdp
  - co2_per_capita
  - co2_per_gdp
  - co2_growth_abs
  - co2_growth_prct
  - coal_co2
  - oil_co2
  - gas_co2
  - cement_co2
  - flaring_co2
  - land_use_change_co2
  - co2_including_luc
  - co2_including_luc_per_capita
  - cumulative_co2
  - cumulative_co2_including_luc
  - methane
  - nitrous_oxide
  - total_ghg
  - primary_energy_consumption
  - energy_per_capita
  - share_global_co2
  - share_global_cumulative_co2
  - trade_co2
  - temperature_change_from_co2

# number of multivariate targets : 26
# covariate_target_variable_name : co2
# number of covariates : 25
# number of time-steps : 275
