task:
  task_name: minutes
  context_window: 2048
  forecast_horizon: 64
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: lt_stock_minutes_multivariate.csv

# number of variates : 6
# number of time-steps : 122110