task:
  task_name: multivariate
  context_window: 32
  forecast_horizon: 6
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: test.csv

# number of variates : 2
# number of time-steps : 100