task:
  context_window: 2048
  forecast_horizon: 64
  handle_missing: interpolate
  normalization_method: standard
  file_name: covariate_energy_minutes_splitsmart_ac_energy.csv
  target_variable_name: unit_consumption
  covariate_variable_names:
  - Current
  - voltage
  - Power_Factor
  - Real_Power
  - room_temp
  - External_temp
  - Humidity

# target_variable_name : unit_consumption
# number of covariates : 7
# number of time-steps : 384440
