task:
  task_name: sparse
  context_window: 12
  forecast_horizon: 4
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: patient_sparse_univariate.csv

# number of variates : 1
# number of time-steps : 8093