model_type: stochastic
python_version: "3.11"
device: cpu
hf_model_name: Salesforce/moirai-1.1-R-base
size: base
bsz: 1
model_size: base
psz: auto
capabilities:
  covariates: past_future
  univariate: true
  multivariate: true
foundation: true
default_hyperparameter_grid: {}
