task:
  context_window: 64
  forecast_horizon: 33
  handle_missing: interpolate
  normalization_method: standard
  file_name: univariate_healthcare_monthly_all_employees_health_care.csv
  target_variable_names:
  - all_employees_health_care_us_bls

# number of targets : 1
# number of time-steps : 436
