task:
  task_name: nature
  context_window: 32
  forecast_horizon: 8
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: soil_nature_univariate.csv

# number of variates : 1
# number of time-steps : 679