task:
  context_window: 2048
  forecast_horizon: 64
  handle_missing: interpolate
  normalization_method: standard
  file_name: multivariate_climate_hourly_madrid_air_pollution.csv
  target_variable_names:
  - BEN
  - CH4
  - CO
  - EBE
  - NMHC
  - 'NO'
  - NO2
  - NOx
  - O3
  - PM10
  - PM25
  - SO2
  - TCH
  - TOL

# number of targets : 14
# number of time-steps : 186240
