task:
  task_name: sales
  context_window: 2048
  forecast_horizon: 64
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: california_hourly_covariate.csv

# number of covariates : 1
# number of time-steps : 52585
