task:
  context_window: 128
  forecast_horizon: 64
  handle_missing: interpolate
  normalization_method: standard
  file_name: multivariate_web_daily_wikipedia_web_traffic.csv
  target_variable_names:
  - 2NE1_zh.wikipedia.org_all-access_spider
  - 2PM_zh.wikipedia.org_all-access_spider
  - 3C_zh.wikipedia.org_all-access_spider
  - 4minute_zh.wikipedia.org_all-access_spider
  - 52_Hz_I_Love_You_zh.wikipedia.org_all-access_spider
  - 5566_zh.wikipedia.org_all-access_spider
  - 91Days_zh.wikipedia.org_all-access_spider
  - A'N'D_zh.wikipedia.org_all-access_spider
  - AKB48_zh.wikipedia.org_all-access_spider
  - ASCII_zh.wikipedia.org_all-access_spider
  - ASTRO_zh.wikipedia.org_all-access_spider
  - Ahq_e-Sports_Club_zh.wikipedia.org_all-access_spider
  - All_your_base_are_belong_to_us_zh.wikipedia.org_all-access_spider
  - AlphaGo_zh.wikipedia.org_all-access_spider
  - Android_zh.wikipedia.org_all-access_spider
  - Angelababy_zh.wikipedia.org_all-access_spider
  - Apink_zh.wikipedia.org_all-access_spider
  - Apple_II_zh.wikipedia.org_all-access_spider
  - As_One_zh.wikipedia.org_all-access_spider
  - B-PROJECT_zh.wikipedia.org_all-access_spider
  - B1A4_zh.wikipedia.org_all-access_spider
  - BDSM_zh.wikipedia.org_all-access_spider
  - BEAST_zh.wikipedia.org_all-access_spider
  - BIGBANG_zh.wikipedia.org_all-access_spider
  - BLACK_PINK_zh.wikipedia.org_all-access_spider
  - BLEACH_zh.wikipedia.org_all-access_spider
  - BTOB_zh.wikipedia.org_all-access_spider
  - Beautiful_Mind_zh.wikipedia.org_all-access_spider
  - Beyond_zh.wikipedia.org_all-access_spider
  - Big_zh.wikipedia.org_all-access_spider
  - Block_B_zh.wikipedia.org_all-access_spider
  - CHAOS;CHILD_zh.wikipedia.org_all-access_spider
  - CHAOS;HEAD_zh.wikipedia.org_all-access_spider
  - CLC_zh.wikipedia.org_all-access_spider
  - CNBLUE_zh.wikipedia.org_all-access_spider
  - DIA_zh.wikipedia.org_all-access_spider
  - Daigo_zh.wikipedia.org_all-access_spider
  - Dear_My_Friends_zh.wikipedia.org_all-access_spider
  - Doctors_zh.wikipedia.org_all-access_spider
  - EGOIST_zh.wikipedia.org_all-access_spider
  - EXID_zh.wikipedia.org_all-access_spider
  - EXO_zh.wikipedia.org_all-access_spider
  - Energy_zh.wikipedia.org_all-access_spider
  - Eric_Nam_zh.wikipedia.org_all-access_spider
  - FAIRY_TAIL_zh.wikipedia.org_all-access_spider
  - FIESTAR_zh.wikipedia.org_all-access_spider
  - FIRST_CLASS_zh.wikipedia.org_all-access_spider
  - Facebook_zh.wikipedia.org_all-access_spider
  - Fantastic_Duo_zh.wikipedia.org_all-access_spider
  - Fate/Grand_Order_zh.wikipedia.org_all-access_spider
  - Fate/Zero_zh.wikipedia.org_all-access_spider
  - Fate/stay_night_zh.wikipedia.org_all-access_spider
  - File:427FW_126.JPG_zh.wikipedia.org_all-access_spider
  - File:Ap_F23_20110324114153669.jpg_zh.wikipedia.org_all-access_spider
  - File:Christian-krohg-leiv-eriksson.jpg_zh.wikipedia.org_all-access_spider
  - File:Sebastiaosalgado2006.jpg_zh.wikipedia.org_all-access_spider
  - File:Zhongxiao_West_Road2.JPG_zh.wikipedia.org_all-access_spider
  - G-Dragon_zh.wikipedia.org_all-access_spider
  - G.NA_zh.wikipedia.org_all-access_spider
  - GFRIEND_zh.wikipedia.org_all-access_spider
  - GNZ48_zh.wikipedia.org_all-access_spider
  - GOT7_zh.wikipedia.org_all-access_spider
  - GUMMY_zh.wikipedia.org_all-access_spider
  - Girl's_Day_zh.wikipedia.org_all-access_spider
  - Goodbye_Mr._Black_zh.wikipedia.org_all-access_spider
  - Google_zh.wikipedia.org_all-access_spider
  - Gu9udan_zh.wikipedia.org_all-access_spider
  - HDMI_zh.wikipedia.org_all-access_spider
  - Hand_Shakers_zh.wikipedia.org_all-access_spider
  - Hisasi_zh.wikipedia.org_all-access_spider
  - Hit_The_Stage_zh.wikipedia.org_all-access_spider
  - Hotel_King_zh.wikipedia.org_all-access_spider
  - I'm_Home_zh.wikipedia.org_all-access_spider
  - I.O.I_zh.wikipedia.org_all-access_spider
  - IKON_zh.wikipedia.org_all-access_spider
  - INFINITE_zh.wikipedia.org_all-access_spider
  - IPhone_zh.wikipedia.org_all-access_spider
  - Ingress_zh.wikipedia.org_all-access_spider
  - Intel740_zh.wikipedia.org_all-access_spider
  - Intel_80386_zh.wikipedia.org_all-access_spider
  - Juksy_zh.wikipedia.org_all-access_spider
  - K.A.R.D_zh.wikipedia.org_all-access_spider
  - KNK_zh.wikipedia.org_all-access_spider
  - KUROMUKURO_zh.wikipedia.org_all-access_spider
  - Kara_zh.wikipedia.org_all-access_spider
  - Kill_Me_Heal_Me_zh.wikipedia.org_all-access_spider
  - Lady_Gaga_zh.wikipedia.org_all-access_spider
  - Legal_high_zh.wikipedia.org_all-access_spider
  - LoveLive!_zh.wikipedia.org_all-access_spider
  - LoveLive!_Sunshine!!_zh.wikipedia.org_all-access_spider
  - Lovelyz_zh.wikipedia.org_all-access_spider
  - Lulu_zh.wikipedia.org_all-access_spider
  - MADTOWN_zh.wikipedia.org_all-access_spider
  - MAMAMOO_zh.wikipedia.org_all-access_spider
  - MONSTA_X_zh.wikipedia.org_all-access_spider
  - Madame_Antoine_zh.wikipedia.org_all-access_spider
  - Mamamoo_zh.wikipedia.org_all-access_spider
  - Mike_D._Angelo_zh.wikipedia.org_all-access_spider
  - Miss_A_zh.wikipedia.org_all-access_spider
  - Missing9_zh.wikipedia.org_all-access_spider
  - Monstar_zh.wikipedia.org_all-access_spider
  - Mrs._Cop_2_zh.wikipedia.org_all-access_spider
  - NBA_zh.wikipedia.org_all-access_spider
  - NCT_zh.wikipedia.org_all-access_spider
  - NEW_GAME!_zh.wikipedia.org_all-access_spider
  - Netflix_zh.wikipedia.org_all-access_spider
  - Niantic_zh.wikipedia.org_all-access_spider
  - ONE_OK_ROCK_zh.wikipedia.org_all-access_spider
  - ONE_PIECE_zh.wikipedia.org_all-access_spider
  - ONE_PIECE_FILM_GOLD_zh.wikipedia.org_all-access_spider
  - Oh_My_Girl_zh.wikipedia.org_all-access_spider
  - Oh_My_Venus_zh.wikipedia.org_all-access_spider
  - PRODUCE_101_zh.wikipedia.org_all-access_spider
  - Page_Turner_zh.wikipedia.org_all-access_spider
  - Pen-Pineapple-Apple-Pen_zh.wikipedia.org_all-access_spider
  - PewDiePie_zh.wikipedia.org_all-access_spider
  - Popu_Lady_zh.wikipedia.org_all-access_spider
  - Pristin_zh.wikipedia.org_all-access_spider
  - Python_zh.wikipedia.org_all-access_spider
  - Qualidea_Code_zh.wikipedia.org_all-access_spider
  - RADWIMPS_zh.wikipedia.org_all-access_spider
  - RAID_zh.wikipedia.org_all-access_spider
  - RWBY_zh.wikipedia.org_all-access_spider
  - Rain_zh.wikipedia.org_all-access_spider
  - ReLIFE_zh.wikipedia.org_all-access_spider
  - Red_Velvet_zh.wikipedia.org_all-access_spider
  - Rewrite_zh.wikipedia.org_all-access_spider
  - Running_Man_zh.wikipedia.org_all-access_spider
  - S.H.E_zh.wikipedia.org_all-access_spider
  - SF9_zh.wikipedia.org_all-access_spider
  - SHINee_zh.wikipedia.org_all-access_spider
  - SISTAR_zh.wikipedia.org_all-access_spider
  - SIXTEEN_zh.wikipedia.org_all-access_spider
  - SMAP_zh.wikipedia.org_all-access_spider
  - SNH48_zh.wikipedia.org_all-access_spider
  - SUPER_LOVERS_zh.wikipedia.org_all-access_spider
  - Schwarzesmarken_zh.wikipedia.org_all-access_spider
  - Secret_Love_zh.wikipedia.org_all-access_spider
  - SpeXial_zh.wikipedia.org_all-access_spider
  - Special:Search_zh.wikipedia.org_all-access_spider
  - Super_Junior_zh.wikipedia.org_all-access_spider
  - Supper_Moment_zh.wikipedia.org_all-access_spider
  - T-ara_zh.wikipedia.org_all-access_spider
  - T.O.P._zh.wikipedia.org_all-access_spider
  - TANet_zh.wikipedia.org_all-access_spider

# number of targets : 145
# number of time-steps : 550
