task:
  task_type: deterministic
  forecast_horizon: 28
  context_window: 512
  max_windows: 20
  max_num_variates: 1
  tuning_loss: mae
  dataset:
    name: univariate/electricity_energy_univariate
    normalize: true
    handle_missing: interpolate
evaluation:
  metrics:
  - mae
  - mase
  - rmse
  - mape
  logging: true
model:
  toto: {}
  lagllama: {}
