task:
  context_window: 32
  forecast_horizon: 8
  handle_missing: interpolate
  normalization_method: standard
  file_name: multivariate_transport_monthly_airline_baggage_complaints.csv
  target_variable_names:
  - Baggage
  - Scheduled
  - Cancelled
  - Enplaned

# number of targets : 4
# number of time-steps : 84
