task:
  task_name: binary
  context_window: 128
  forecast_horizon: 55
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: absent_binary_univariate.csv

# number of variates : 1
# number of time-steps : 740