task:
  name: retail_categorical_univariate
  context_window: 2048
  forecast_horizon: 64
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: retail_categorical_univariate.csv
