task:
  task_type: deterministic
  forecast_horizon: 4
  context_window: 20
  dataset:
    name: multivariate/multivariate_test
    normalize: true
    handle_missing: interpolate
evaluation:
  metrics: [mae, mase, rmse, mape]
  tuning_loss: mae
  max_windows: 5
  max_num_variates: 2
model:
  arima:
    p: [1, 2]
    d: [1]
    q: [1, 2]
    s: [2]
