task:
  context_window: 45
  forecast_horizon: 16
  handle_missing: interpolate
  normalization_method: standard
  file_name: multivariate_sales_weekly_walmart_sales.csv
  target_variable_names:
  - Weekly_Sales
  - Holiday_Flag
  - Temperature
  - Fuel_Price
  - CPI
  - Unemployment

# number of targets : 6
# number of time-steps : 143
