task:
  task_name: nonstationary
  context_window: 512
  forecast_horizon: 64
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: software_nonstationary_univariate.csv

# number of variates : 1
# number of time-steps : 1827