# Main configuration for the benchmarking pipeline
# This file provides sensible defaults for all configuration options



evaluation:
  task_path: 'multivariate/baggage_100_multivariate'
  tuning_loss: mae
  max_windows: 20
  max_num_variates: 10
  num_samples: 100
  num_quantiles: 10
  point_forecast_statistic: mean

model:
  # # Universal Models
  # lafn_hybrid: {}

  # seasonal_naive: 
  #   sp: [12, 24]

  # Deterministic Models
  # arima:
  #   p: [1, 2]
  #   d: [1]
  #   q: [1, 2]
  #   s: [2]

  # croston_classic:
  #   alpha: [0.1, 0.3, 0.5]
  #   gamma: [0.1, 0.3, 0.5]

  # exponential_smoothing:
  #   trend: [null]
  #   damped_trend: [false, true]
  #   seasonal: [null]
  #   seasonal_periods: [12, 24]

  # lstm:
  #   units: [32]
  #   layers: [1]
  #   dropout: [0.1, 0.3, 0.5]
  #   learning_rate: [0.01, 0.001, 0.0001, 000001]
    

  # prophet:
  #   seasonality_mode: [additive]
  #   changepoint_prior_scale: [0.05]
  #   seasonality_prior_scale: [10.0]

  # random_forest:
  #   n_estimators: [10]
  #   max_depth: [2]

  
  # svr:
  #   kernel: [rbf]
  #   C: [1.0]
  #   epsilon: [0.1]
  #   gamma: [scale]

  # theta:
  #   sp: [12]
  #   theta_method: [correlation_optimal]
  #   use_reduced_rank: [false]

  # varmax:
  #   p: [1, 2]
  #   q: [1, 2]
  #   trend: [c, t, ct]  

  # xgboost:
  #   n_estimators: [200]
  #   max_depth: [4]
  #   learning_rate: [0.05]


  

  moment: {}
  timesfm: {}
  tiny_time_mixer: {}

  # Stochastic models
  chronos: {}
  deepar: {}
  moirai: {}
  moirai_moe: {}
  lagllama: {}
  toto: {}
  tabpfn: {}
  

