evaluation:
  task_path: multivariate/*
  tuning_loss: mae
  max_windows: 4
  max_num_variates: 10
  num_samples: 100
  num_quantiles: 10
  point_forecast_statistic: mean
model:
  random_forest:
    n_estimators: [10]
    max_depth: [2]
