evaluation:
  task_path: 'multivariate/baggage_100_multivariate'
  tuning_loss: mae
  max_windows: 4
  max_num_variates: 10
  num_samples: 100
  num_quantiles: 10
  point_forecast_statistic: mean
model:
  lstm:
    learning_rate: [0.01, 0.001, 0.0001]

