evaluation:
  task_path: "covariate/advertising_sales_covariate"
  tuning_loss: mae
  max_windows: 4
  max_num_variates: 50
  num_samples: 100
  num_quantiles: 10
  point_forecast_statistic: mean

model:
  # Deterministic Models

  #prophet:
  #  seasonality_mode: [additive]
  #  changepoint_prior_scale: [0.05]
  #  seasonality_prior_scale: [10.0]
  varmax:
    p: [1, 2]
    q: [1, 2]
    trend: [c, t]
