task:
  task_name: manufacturing
  context_window: 64
  forecast_horizon: 30
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: inventories_manufacturing_univariate.csv

# number of variates : 1
# number of time-steps : 402