task:
  name: madrid_transport_multivariate
  context_window: 2048
  forecast_horizon: 64
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: madrid_transport_multivariate.csv
