task:
  context_window: 2048
  forecast_horizon: 64
  handle_missing: interpolate
  normalization_method: standard
  file_name: multivariate_manufacturing_seconds_skab.csv
  multivariate_target_variable_names:
  - Accelerometer1RMS
  - Accelerometer2RMS
  - Current
  - Pressure
  - Temperature
  - Thermocouple
  - Voltage
  - Volume Flow RateRMS
  covariate_target_variable_name: Pressure
  covariate_variable_names:
  - Accelerometer1RMS
  - Accelerometer2RMS
  - Current
  - Temperature
  - Thermocouple
  - Voltage
  - Volume Flow RateRMS

# number of multivariate targets : 8
# covariate_target_variable_name : Pressure
# number of covariates : 7
# number of time-steps : 9961
