task:
  task_name: economics
  context_window: 1024
  forecast_horizon: 64
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: goldindia_economics_multivariate.csv

# number of variates : 5
# number of time-steps : 4024