task:
  task_name: count
  context_window: 2048
  forecast_horizon: 64
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: madrid_count_multivariate.csv

# number of variates : 14
# number of time-steps : 181753