task:
  task_name: sales
  context_window: 32
  forecast_horizon: 6
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: solar_100_covariate.csv

# number of covariates : 1
# number of time-steps : 100
