task:
  task_name: sales
  context_window: 256
  forecast_horizon: 22
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: solar_500_covariate.csv

# number of covariates : 1
# number of time-steps : 500
