task:
  task_name: longest
  context_window: 2048
  forecast_horizon: 64
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: lt_stock_longest_multivariate.csv

# number of variates : 6
# number of time-steps : 122110