task:
  task_name: software
  context_window: 512
  forecast_horizon: 64
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: batadal_software_multivariate.csv

# number of variates : 44
# number of time-steps : 1741