model_type: deterministic
python_version: '3.12'
hf_model_name: ibm-granite/granite-timeseries-ttm-r2
capabilities:
  covariates: past_future
  univariate: true
  multivariate: true
foundation: true
default_hyperparameter_grid: {}
