task:
  task_type: stochastic
  forecast_horizon: 4
  context_window: 42
  dataset:
    name: multivariate/baggage_100_multivariate
    normalize: true
    handle_missing: interpolate
evaluation:
  metrics:
  - crps
  - quantile_score
  - weighted_interval_score
  - mae
  - rmse
  tuning_loss: mae
  max_windows: 20
  max_num_variates: 10
model:
  chronos: {}
  deepar: {}
  lagllama: {}
  moirai: {}
  moirai_moe: {}
  toto: {}
