task:
  task_name: sales
  context_window: 32
  forecast_horizon: 8
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: gdp_years_covariate.csv

# number of covariates : 1
# number of time-steps : 48
