task:
  name: employees_healthcare_univariate
  context_window: 128
  forecast_horizon: 8
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: employees_healthcare_univariate.csv
