task:
  task_name: healthcare
  context_window: 64
  forecast_horizon: 33
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: employees_healthcare_univariate.csv

# number of variates : 1
# number of time-steps : 427