task:
  context_window: 2048
  forecast_horizon: 64
  handle_missing: interpolate
  normalization_method: standard
  file_name: covariate_climate_hourly_madrid_air_pollution.csv
  target_variable_name: PM25
  covariate_variable_names:
  - BEN
  - CH4
  - CO
  - EBE
  - NMHC
  - 'NO'
  - NO2
  - NOx
  - O3
  - PM10
  - SO2
  - TCH
  - TOL

# target_variable_name : PM25
# number of covariates : 13
# number of time-steps : 186240
