task:
  task_name: sales
  context_window: 32
  forecast_horizon: 8
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: baggage_sales_multivariate.csv

# number of variates : 4
# number of time-steps : 84