task:
  task_name: sales
  context_window: 200
  forecast_horizon: 16
  dataset:
    handle_missing: interpolate
    normalize: true
    file_name: currency_dense_covariate.csv

# number of covariates : 1
# number of time-steps : 312
